### ISSUE TITLE
Na začátku roku 2017 jsem měl na chalupě 20m3  dřeva na topení. Rozhodl jsem se, že každý rok stopím 10%  zásoby, kterou budu mít na začátku roku. Kromě toho si během roku nařežu 1m3  na topení sám. Na začátku kterého roku se moje zásoba dostane poprvé pod 11m3 ?

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-zdm-rozstrel#11]
<img width="856" alt="na zacatku roku 2017 jsem mel na chalupe 20m3 dreva na topeni rozhodl jse" src="https://user-images.githubusercontent.com/9153692/34920132-ffc4f0e0-f96d-11e7-8c0b-4187a2a80072.png">

**Comment by MSKL** [comment]
<img width="587" alt="snimek obrazovky 2018-01-14 v 21 03 51" src="https://user-images.githubusercontent.com/9153692/34920154-74247fb4-f96e-11e7-814e-a6e3db6297a1.png">
Asi 2039?

**Comment by jstorm31** [comment]
Jojo, souhlasím. Jinak rekurzivně se dá takto: 😄 
```
function rec (n) {
	if (n === 0) return 20
	return rec(n-1) * 0.9 + 1
}
```

**Comment by MSKL** [comment]
Vypočítal jsem tu rekurenci:
Nechť K=9/10 pak rekurence je:
**an = 10*K^n + 10**
Teď už je to potřeba asi jen zkoušet dosazovat?

**Comment by MSKL** [comment]
pro n = 22 je to míň než 11, takže 2017+22 = 2039

**Comment by jstorm31** [comment]
Jo, a jak jsi ji teda sestavil? Takže rychlejší je prostě si to nakódit v konzoli prohlížeče 😄

**Comment by MSKL** [comment]
dělal jse to pro K, protože se mi to nechtělo počítat s 9/10:
přidružená homogenní rovnice = 10*K^n
partikulární řešení = 1/(1-K)
řešení soustavy po dosazení poč. podmínek = 10*K^n + 10
