### ISSUE TITLE
Určete počet vyjádření GCD(66, 42)

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-zdm-rozstrel#13]
![urcete pocet vyjadreni gcd 66 42](https://user-images.githubusercontent.com/16023539/34920651-2c75771a-f976-11e7-9958-13e89f3638ee.jpg)

Je 3 dobře?

Řešení mi vyšlo _(2 + k * 7, -3 - k * 11)_

**Comment by jstorm31** [comment]
Aha, tak prý 5. Kde mám chybu?

**Comment by MSKL** [comment]
gcd(66, 42) = 6
bezoutova rovnice:
- (2)\*66 + (-3)\*42 = 6
přidružená homogenní rovnice:
- (-7)\*66 + (11)\*42 = 0
množina řešení pro k ze Z:
- (A, B) = (2, -3) + k\*(-7, 11)
pro |A+B| <=10 platí k = {-2, -1, 0, 1, 2}
tedy (16, -25), (9, -14), (2, -3), (-5, 8), (-12, 19)
