### ISSUE TITLE
Zkouška z předmětu BI-ZDM je naplánována do místností A,B,C , pro dozor u zkoušky jsou k dispozici učitelé P,Q,R,S 

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-zdm-rozstrel#17]
<img width="862" alt="zkouska z predmetu bi-zdm je naplanovana do mistnosti a b c pro dozor u zkousky jsou k dispozici ucitele p q r s" src="https://user-images.githubusercontent.com/9153692/34922293-4df2bf02-f98e-11e7-8e9d-651e03e64cd5.png">

**Comment by MSKL** [comment]
napadá mě udělat si virtuální 4 místnosti -> mám 4! možností jak tam umístit učitele a tu jednu místnost pak budu mergovat se 3 ostatními takže 4!*3?

**Comment by MSKL** [comment]
Asi by to mělo být 4!/(2!*1!*1!) = 4*3*2/2 = 12??

**Comment by MSKL** [comment]
Asi jo, to dává smysl
To je jako vzít 4! a pak jednu dvojitci zrušit přes 2!.

**Comment by MSKL** [comment]
Nebo je to k!\*S(n,k) což by bylo 3!*6 = 36

**Comment by jstorm31** [comment]
Jo, má to vyjít 36. https://www.fit-wiki.cz/_media/škola/předměty/bi-zdm/zdm_test_2014-12-3_11/9.png?cache=

Akorát si říkám, proč S(n, k), které je definované jako _Máme k **stejných** krabiček a rozdělujeme mezi ně n různých objektů_. A ty třídy A, B, C jsou různé. Btw. jak to Stirlingovo číslo? Přes rekurenci?
