### ISSUE TITLE
Známá osoba českého show businessu H. P. 

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-zdm-rozstrel#18]
<img width="859" alt="znama osoba ceskeho show businessu h p hodla nasadit n" src="https://user-images.githubusercontent.com/9153692/34923014-dafacb7a-f997-11e7-801d-29b9255fdae0.png">

**Comment by MSKL** [comment]
<img width="862" alt="znama osoba ceskeho show businessu h p hodla nasadit na nov" src="https://user-images.githubusercontent.com/9153692/34923235-57993516-f99a-11e7-8301-7fa128c4d39e.png">

**Comment by jstorm31** [comment]
110

**Comment by MSKL** [comment]
<img width="222" alt="snimek obrazovky 2018-01-15 v 12 21 14" src="https://user-images.githubusercontent.com/9153692/34940182-e63cbeec-f9ee-11e7-896f-1753810c4fde.png">
