### ISSUE TITLE
Použijte Mistrovskou metodu k získání asymptotického těsného odhadu pro posloupnost splňující rekurenci t(n)=8t(n/2)+(n⋅logn)3

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-zdm-rozstrel#2]
![pouzijte mistrovskou metodu k ziskani asymptotickeho tesneho odhadu pro posloupnost splnujici rekurenci t n 8t n 2 n logn 3](https://user-images.githubusercontent.com/16023539/34917349-7f587706-f945-11e7-9746-382f018055d3.jpg)

**Comment by MSKL** [comment]
nelze

**Comment by jstorm31** [comment]
A nevíš proč? 🤔

**Comment by jstorm31** [comment]
Pro (MM3) má platit:
_n^3 * log(n/2)^3 <= c * n^3 * log(n)^3_.
Ta konstanta c nejde najít?

**Comment by MSKL** [comment]
<img width="862" alt="pouzijte mistrovskou metodu k ziskani asymptotickeho tesneho odhadu pro posloupnost splnujici rekurenci t n 8t n 2 n logn 3" src="https://user-images.githubusercontent.com/9153692/34918280-877a1f4c-f950-11e7-8737-bee3f5b7e02c.png">

**Comment by MSKL** [comment]
proč nevím 👎

**Comment by jstorm31** [comment]
Přednáška 9, slide 23: 

> Pokud je rozdíl mezi funkcemi menší než polynomiální, nelze tuto
metodu použít!
