### ISSUE TITLE
Určete hodnotu mocniny 123456789(mod43)

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-zdm-rozstrel#3]
![urcete hodnotu mocniny 123456789 mod43](https://user-images.githubusercontent.com/16023539/34917364-b16fa89a-f945-11e7-8a27-eeb34e060919.jpg)

**Comment by MSKL** [comment]
12345 % 43 = 4 => mám 4^6789 mod 43
43 je prvočíslo => malá fermatova věta
- platí, že 4^42 = 1 mod 43
=> zkrátím tím tu mocninu a mám 4^27 mod 43
teď udělám přes mocniny dvojky výsledek který bude 4^16*4^8*4^2*4 mod 43. Tohle dopočítáš a máš výsledek
