### ISSUE TITLE
Můj normální celkový objem tělesné vody je asi 48 litrů

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-zdm-rozstrel#4]
![muj normalni celkovy objem telesne vody je asi 48 litru](https://user-images.githubusercontent.com/16023539/34917372-c742f776-f945-11e7-925b-a1d79df72179.jpg)

**Comment by MSKL** [comment]
b), jak to spočítt nevím

**Comment by MSKL** [comment]
resp. na těch kompech je distro a třeba python by tam měl jít
někdo mi tvrdil že možná i Mathematica, tak to by bylo kdyžtak řešení

**Comment by jstorm31** [comment]
A zkoušel sis sestavit tu rekurenci? Napsal jsem si to jako:
_a_0 = 48000
a_n = 999/1000*a_(n-1) + 45/1000
a hledá se a_500. Ale nevím, jestli to je dobře...

**Comment by MSKL** [comment]
<img width="505" alt="snimek obrazovky 2018-01-14 v 18 47 26" src="https://user-images.githubusercontent.com/9153692/34918909-651bd304-f95b-11e7-8b10-3c796cd93860.png">
