### ISSUE TITLE
urcete kolika ruznymi zpusoby lze osoby a b c d a e rozsadit ke

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-zdm-rozstrel#6]
<img width="862" alt="urcete kolika ruznymi zpusoby lze osoby a b c d a e rozsadit ke" src="https://user-images.githubusercontent.com/9153692/34918315-dc9f1856-f950-11e7-9fb3-d0afbdda15ca.png">

**Comment by MSKL** [comment]
možná 30?

**Comment by jstorm31** [comment]
Myslím, že to bylo takhle. 2 různé stoly (určené osobou A a E). U jednoho stolu můžou sedět:

- 4 lidi: (4-1)! = 6 možností
- 3 lidi (jeden fixně, např. A + vybíráš 2 lidi ze 3): 3*(3-2)! = 6 možností

Celkem tedy (6 + 6) * 2 = 24 možností. Rozesazení kolem stolu určují tzv. cyklické permutace (n-1)!.

**Comment by jstorm31** [comment]
Nebo https://github.com/MSKL/fit-bi-zdm-midterm/issues/1.
