### ISSUE TITLE
necht a b c jsou nejaka cela cisla uvazujme relaci delitelnosti beze zbytku znacene na mnozine celych cisel vyznacte vsechna pravdiva tvrzeni v nasledujici nabidce

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-zdm-rozstrel#7]
<img width="865" alt="necht a b c jsou nejaka cela cisla uvazujme relaci delitelnosti beze zbytku znacene na mnozine celych cisel vyznacte vsechna pravdiva tvrzeni v nasledujici nabidce" src="https://user-images.githubusercontent.com/9153692/34918318-e951f0be-f950-11e7-9768-1b4968f6983c.png">

**Comment by jstorm31** [comment]
1. Určitě false. Funguje to akorát gcd(a, b) = gcd(a, a+b)
2. Podle mě dobře, to nemusí platit. Máš nějaký protipříklad?
3. Taky bych řekl dobře. Protipříklad c = 6, a = 2, b = 3.
4. Asi špatně? 😄

**Comment by MSKL** [comment]
1. protipříklad:
- gcd(12,4) = 2, gcd(12,8) = 4
4. protipříklad:
- gcd(12,3) = 3, c = 4, c*3 <= 12 
=> mělo by platit, že gcd(12, 3) == gcd(12, 12) což neplatí (3 != 12)
