### ISSUE TITLE
Z uvedených rovnic označte všechny lineární rekurentní rovnice (i takové, které lze ekvivalentní úpravou na lineární rekurentní rovnice převést).

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-zdm-rozstrel#8]
![z uvedenych rovnic oznacte vsechny linearni rekurentni rovnice i takove ktere lze ekvivalentni upravou na linearni rekurentni rovnice prevest](https://user-images.githubusercontent.com/16023539/34919640-a6906046-f967-11e7-9fb6-46c4428d8fc4.jpg)
 Podle čeho poznám? 🤔

**Comment by MSKL** [comment]
3 ne - sqrt(an) nejde protože, to musý být ve tvaru K*an, kde K je nějaká konstanta

**Comment by jstorm31** [comment]
No ale tam se nepíše, že mají být konstantní... Ale asi se to myslí.
